# Generated by Django 5.1.3 on 2025-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_ordermodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
